// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMQ2KpJBuTUrIhT2fx0IWg3aq5nCN_ELg',
    appId: '1:892681363059:web:469e6d6082bfa092a11406',
    messagingSenderId: '892681363059',
    projectId: 'chat-app-c09ac',
    authDomain: 'chat-app-c09ac.firebaseapp.com',
    storageBucket: 'chat-app-c09ac.firebasestorage.app',
    measurementId: 'G-PYMT8KVG1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Bl6zd9Hdu06EY52i6TZn-PXqlx1uobM',
    appId: '1:892681363059:android:f8b3128c3c48654fa11406',
    messagingSenderId: '892681363059',
    projectId: 'chat-app-c09ac',
    storageBucket: 'chat-app-c09ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5L1mxwfGpcR1E9gOL7COEjzg2xwARecg',
    appId: '1:892681363059:ios:4ff814f1f5d9b5d0a11406',
    messagingSenderId: '892681363059',
    projectId: 'chat-app-c09ac',
    storageBucket: 'chat-app-c09ac.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5L1mxwfGpcR1E9gOL7COEjzg2xwARecg',
    appId: '1:892681363059:ios:4ff814f1f5d9b5d0a11406',
    messagingSenderId: '892681363059',
    projectId: 'chat-app-c09ac',
    storageBucket: 'chat-app-c09ac.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMQ2KpJBuTUrIhT2fx0IWg3aq5nCN_ELg',
    appId: '1:892681363059:web:e861e6acf012ed86a11406',
    messagingSenderId: '892681363059',
    projectId: 'chat-app-c09ac',
    authDomain: 'chat-app-c09ac.firebaseapp.com',
    storageBucket: 'chat-app-c09ac.firebasestorage.app',
    measurementId: 'G-Y4YZNHWPEF',
  );
}
